apiVersion: v1
data:
  sidecar.automountServiceAccountToken: "true"
  sidecar.container: |
    command:
    - argo-spark-plugin
    image: argo-spark-plugin:v1
    name: spark-executor-plugin
    ports:
    - containerPort: 3018
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
  name: spark-executor-plugin